### ISSUE TITLE
Dla Radka

### ISSUE THREAD

**Issue by surjak** [surjak/EmailAlert#20]
Radek tu lista rzeczy którą  mógłbyś zrobić

**Comment by surjak** [comment]
Strona startowa - zrobić żeby to jakoś ładnie wyglądałom dodać jakies zdj itd itp
![image](https://user-images.githubusercontent.com/49077485/83052400-8e63ff00-a04f-11ea-913a-904deb0b355f.png)

**Comment by surjak** [comment]
Dodać jakieś ładniejsze CSSy na reszcie HTMLi

**Comment by surjak** [comment]
Tutaj jest wykomentowany kod który wysyła maile i pobiera dane z API, mógłbyś utworzyć jakiegos timera co uruchamia ten kod co jakiś czas. Uwaga: mamy 100 requestów do API także używaj z rozsądkiem XD dla każdego usera wysyłany jest request dlatego nie dodawaj jakos wiele userów, a jak Ci się skończą requesty to wygeneruj własny klucz ewentualnie
![image](https://user-images.githubusercontent.com/49077485/83052598-d8e57b80-a04f-11ea-81bd-064157995fc2.png)

**Comment by surjak** [comment]
Przy dodawaniu nowych constraintów dodawany jest zawsze nowy i wtedy user na np dwa do jednego zjawiska, weź to zrób tak że jak user dodaje do tego samego zjawiska to się nadpisuje jego stare, tak żeby było max 1 do jednego zjawiska. Jest taka funkcja jak updateOrInsert, możesz z nią spróbować
![image](https://user-images.githubusercontent.com/49077485/83052889-3aa5e580-a050-11ea-9f3f-9d18f1851d2d.png)

**Comment by surjak** [comment]
Po kliknięciu przysicku ALERT jeśli użytkownik jest zalogowany to żeby nie znikały z Menu "Panel" oraz "Configuration" z prawej strony. Ogarniesz o co chodzi, jak nie to pisz
![image](https://user-images.githubusercontent.com/49077485/83053129-88bae900-a050-11ea-8f94-fda06de24b7c.png)

**Comment by surjak** [comment]
W bazie jest gotowa kolumna z czasem Unixowym która wskazuje kiedy był wysłany ostatni mail dla usera, przy wysyłaniu maili trzeba zrobić updatowanie tej kolumny na aktualny czas oraz sprawdzanie czy minęło 12h od ostatniego wysłania i wtedy ewentualnie wysłać maila, w przeciwnym razie nie wysyłać. Trzeba to ładnie zrobić na streamach, funkcje takie jak map, filter, flatMap itp ---- > LastDate
![image](https://user-images.githubusercontent.com/49077485/83053433-febf5000-a050-11ea-91d5-942cedca574d.png)

**Comment by surjak** [comment]
Reszta działa elegancko więc to chyba wszystko. I proszę... pamietaj o tym limicie do API, jeśli załadujesz baz userami to raptem odpalisz apkę 2 razy i limit się skonczy także przed pracą usuń użytkoników z bazy (DataGrip i usuń), zostaw sobie tak z trzech. Jak skończy Ci się limit to wygeneruj własny klucz i podmień z kluczem Andrzeja , zakomentuj wtedy jego bo się przyda

**Comment by RadekKpc** [comment]
> Strona startowa - zrobić żeby to jakoś ładnie wyglądałom dodać jakies zdj itd itp
> ![image](https://user-images.githubusercontent.com/49077485/83052400-8e63ff00-a04f-11ea-913a-904deb0b355f.png)

Zrobione

**Comment by RadekKpc** [comment]
> Po kliknięciu przysicku ALERT jeśli użytkownik jest zalogowany to żeby nie znikały z Menu "Panel" oraz "Configuration" z prawej strony. Ogarniesz o co chodzi, jak nie to pisz
> ![image](https://user-images.githubusercontent.com/49077485/83053129-88bae900-a050-11ea-8f94-fda06de24b7c.png)

 Zrobione jak cos zaraz pull request poleci

**Comment by RadekKpc** [comment]
> Tutaj jest wykomentowany kod który wysyła maile i pobiera dane z API, mógłbyś utworzyć jakiegos timera co uruchamia ten kod co jakiś czas. Uwaga: mamy 100 requestów do API także używaj z rozsądkiem XD dla każdego usera wysyłany jest request dlatego nie dodawaj jakos wiele userów, a jak Ci się skończą requesty to wygeneruj własny klucz ewentualnie
> ![image](https://user-images.githubusercontent.com/49077485/83052598-d8e57b80-a04f-11ea-81bd-064157995fc2.png)

Zrobione wyrzuca tylko błąd przy sendEmail

**Comment by RadekKpc** [comment]
Naprawione trzeba było antywirusa wyłączyć.

**Comment by RadekKpc** [comment]
> Naprawione trzeba było antywirusa wyłączyć.

Zrobiłem Osobny micro-service odpowiadający za wysyłanie POSTa na odpowiedni end-point aplikacji, który uruchamia funkcje wysyłającą emalie

**Comment by RadekKpc** [comment]
> W bazie jest gotowa kolumna z czasem Unixowym która wskazuje kiedy był wysłany ostatni mail dla usera, przy wysyłaniu maili trzeba zrobić updatowanie tej kolumny na aktualny czas oraz sprawdzanie czy minęło 12h od ostatniego wysłania i wtedy ewentualnie wysłać maila, w przeciwnym razie nie wysyłać. Trzeba to ładnie zrobić na streamach, funkcje takie jak map, filter, flatMap itp ---- > LastDate
> ![image](https://user-images.githubusercontent.com/49077485/83053433-febf5000-a050-11ea-91d5-942cedca574d.png)

Zrobione, trochę trzeba było zmienić model bazy i pokombinować z czasem unixowym, ale jest ok.

**Comment by surjak** [comment]
Dobra robota 😄
